[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "amarelli"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "webdavclient3",
    "xxhash",
    "nmcli",
    "flask",
]

[tool.setuptools]
py-modules = ["cli", "config", "log", "cache", "database", "webdav_uploader", "wifi", "flask_app", "spidev", "gpiozero", "Pillow"]

[project.scripts]
amarelli = "cli:main"
