[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "amarelli"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "webdavclient3",
    "xxhash",
    "nmcli",
    "flask",
    "gpiozero",
    "Pillow",
]

[project.optional-dependencies]
raspberry-pi = [
    "spidev",
    "lgpio",
    "RPi.GPIO",
]

[tool.setuptools]
package-dir = {"" = "software"}
py-modules = ["backup", "cache", "config", "database", "display", "eventbus", "exceptions", "flask_app", "keylistener", "log", "main", "menu", "models", "webdav_uploader", "wifi"]

[project.scripts]
amarelli = "main:main"
